import{a as p,S as m,i as l}from"./assets/vendor-67BWzQEt.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const h="51414805-32578d6fb6ee3cb7948c7bdf3";function y(o){return p("https://pixabay.com/api/",{params:{key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data)}const c=document.querySelector(".gallery"),u=document.querySelector(".loader");let a=null;function g(o){const r=o.map(({webformatURL:i,largeImageURL:n,tags:e,likes:t,views:s,comments:f,downloads:d})=>`<li class="gallery-item">
            <a href="${n}">
                <img src="${i}" alt="${e}"/>
            </a>
        <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${f}</p>
        <p><b>Downloads:</b> ${d}</p>
        </li >
        `).join("");c.insertAdjacentHTML("beforeend",r),a?a.refresh():a=new m(".gallery a",{captionsData:"alt",captionDelay:250})}function b(){c.innerHTML=""}function L(){u.classList.remove("hidden")}function S(){u.classList.add("hidden")}const $=document.querySelector(".form"),q=document.querySelector(".search-input");$.addEventListener("submit",x);function x(o){o.preventDefault();const r=q.value.trim();if(!r){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(),L(),y(r).then(i=>{i.hits.length===0?l.info({message:"No images found. Try a different search term.",position:"topRight"}):(g(i.hits),new SimpleLightbox(".gallery a").refresh())}).finally(()=>{S()})}
//# sourceMappingURL=index.js.map
